adding director entity and dao + class diagram
xjurko/PA165_2021 pull request #15
Opened 2021-04-06 19:12 UTC by sandarichard

Added class diagram, director entity, directordao and directerdaoimpl

2021-04-06 19:46 UTC, xjurko reviewed
please add source files for diagram and include diagram in the readme

2021-04-06 19:49 UTC, xjurko reviewed
![image](https://user-images.githubusercontent.com/25619680/113769959-df3d8d00-9721-11eb-9759-28b9f6a4d5bd.png)
Movie entity seems to be incomplete

2021-04-06 19:51 UTC, xjurko reviewed
![image](https://user-images.githubusercontent.com/25619680/113770225-2af03680-9722-11eb-8160-f09bb2b40b40.png)
should Actor and movie have the same kind of bidirectional mapping as director and movie ?

2021-04-07 05:10 UTC, phoenixday commented on persistence/src/main/java/cz/muni/fi/pa165/dao/DirectorDao.java
>      void store(Director d);
maybe leave only "create", like xjurko said

2021-04-07 05:38 UTC, phoenixday reviewed
... also hashcode()

2021-04-07 08:49 UTC, lsolodkova commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Director.java
>      public void setName(String fullName) {
Will be better to use Lombok annotations instead of creating getters/setters manually

2021-04-07 14:16 UTC, xjurko approved these changes
lgtm

2021-04-07 14:18 UTC, xjurko requested changes
![image](https://user-images.githubusercontent.com/25619680/113881507-c7671700-97bc-11eb-8084-bff78bda884b.png)
tehre is still some placeholder stuff

2021-04-07 19:13 UTC, merged