added Actor, ActorDao, ActorDaoImpl
xjurko/PA165_2021 pull request #9
Opened 2021-04-03 19:20 UTC by phoenixday

2021-04-03 19:24 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    //private String caption; // is it the path to image?
pls remove irrelevant code instead of commenting out - to answer the question though - in the movie entity this refers to a short description of movie

2021-04-03 19:26 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    @Enumerated(EnumType.STRING)
actor should probably not be referencing genres directly - this relation will be transitive via the movies this actor played in

2021-04-03 19:28 UTC, xjurko requested changes
few comments otherwise lgtm

2021-04-03 19:28 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    //private String caption; // is it the path to image?
pls remove irrelevant code instead of commenting out - to answer the question though - in the movie entity this refers to a short description of movie

2021-04-03 19:28 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    @Enumerated(EnumType.STRING)
pls remove irrelevant code instead of commenting out - to answer the question though - in the movie entity this refers to a short description of movie

2021-04-04 07:12 UTC, xjurko requested changes

2021-04-04 07:12 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    private Set<Genre> genres;
Actor itself should not be referencing genres - this relation is transitive via the movie entity

2021-04-04 07:29 UTC, phoenixday commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    private Set<Genre> genres;
okay, also i'm not sure, should there be methods addMovie and removeMovie? (lines 92-97)

2021-04-04 07:33 UTC, xjurko commented on persistence/src/main/java/cz/muni/fi/pa165/entity/Actor.java
> +    private Set<Genre> genres;
yeah those can be there

2021-04-04 08:03 UTC, xjurko approved these changes
lgtm !

2021-04-04 15:09 UTC, lsolodkova approved these changes

2021-04-04 15:19 UTC, merged